@startuml

skinparam classAttributeIconSize 0
title Strategy Pattern

class Context{

- operation : Strategy

  operate()


}







interface  Strategy <<interface>>{
+ algorithmus()
}

Context ->  Strategy

Strategy <|.. CongreteStrategyA
Strategy <|.. CongreteStrategyB


@enduml